### ISSUE TITLE
Finish Database

### ISSUE THREAD

**Issue by DoubleBond** [DoubleBond/AnotherOne#6]
I'll need to have you guys enter all data of sections for a course that is on a software engineer's course sequence.

I would like to have this done immediately so that I could copy the data onto summer 2016 and fall 2016, and make some real schedules

**Comment by Rollingball** [comment]
The tutorials for ENGR201 are only had every 2 weeks. 2 sections share the same classroom and time, but not same date. How do we differentiate?

**Comment by DoubleBond** [comment]
just add the other one on another weekday.

**Comment by Rollingball** [comment]
I added all ENGR and basic science courses in course sequence and that are offered in Winter 2016

**Comment by DoubleBond** [comment]
Do you believe the database is complete? That it has 99% of all course related sections for software engineer. Even if the course is not provided in winter. If it's missing, make your own fake section. I will copy the semesters to fall 2016 and summer 2016. once you double check I will duplicate the data over all semesters. Correcting the faults later on will be a hassle if you dont double check.

**Comment by Rollingball** [comment]
Not completed yet, still needs classes missing from winter 2016 + technical electives. Will work on after Tuesday midterm.

**Comment by DoubleBond** [comment]
Please double check every time and date. Make sure that there is no section that has no lectures.
