### ISSUE TITLE
Grade evaluation does not work Mr Eric Payette. Need to optimize the code. 

### ISSUE THREAD

**Issue by DoubleBond** [DoubleBond/AnotherOne#8]
Home page takes at least 6 seconds to load, reduce to maximum 2 seconds

**Comment by mosquitodawg** [comment]
Ill work on it probably monday/tuesday

**Comment by DoubleBond** [comment]
Needs to be done asap.

**Comment by mosquitodawg** [comment]
Gonna try to do it for tonight
